In [1]:
%matplotlib inline

import numpy as np
import sympy as sp  # 符號行運算
import matplotlib.pyplot as plt

## 向量基本運算

In [2]:
# list很像向量

u = [1, 2, 3]
v = [4, 5, 6]

In [3]:
u + v

[1, 2, 3, 4, 5, 6]

In [4]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

In [5]:
u + v # 比較像數學的向量了

array([5, 7, 9])

In [6]:
1.7 * u # 也可以做純量乘法

array([1.7, 3.4, 5.1])

- Rank 0 tensor: Scalar eg: R, C
- Rank 1 tensor: vector(a list of scalars): [1, 2, 3]
- Rank 2 tensor: Matrix 矩陣(a list of vectors): [[1, 2, 3], [4, 5, 6]  
用 rank 的方法就可以為高維的圖形命名了。

## 矩陣:
\left[\begin{martix} 1 & 2 & 3 \\ 4 & 5 & 6 {martix}\end\right**

In [7]:
egg = [ [1, 2, 3], [4, 5, 6] ] # python 是先列(橫)後行(縱)

In [8]:
# 但記住剛才不能運算，要先轉成 numpy 的 array。
A = np.array(egg)

In [9]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
B = np.array([[1, 2], [2, 1], [1, 1]])

In [11]:
B

array([[1, 2],
       [2, 1],
       [1, 1]])

矩陣乘法: 用```@```。

In [12]:
A@B

array([[ 8,  7],
       [20, 19]])

In [13]:
x = np.array([[0], [1], [2]])
# same as np.array([0, 1, 2])，但上面的比較正確。

In [14]:
x.shape

(3, 1)

In [15]:
A@x

array([[ 8],
       [17]])

In [16]:
y = np.array([0, 1, 2])
A@y
# notice the difference compare to up

array([ 8, 17])

## sympy

In [17]:
1/2 + 1/3

0.8333333333333333

想要表示成分數:

In [18]:
sp.Rational(1, 2) + sp.Rational(1, 3)

5/6

In [19]:
from sympy import S
# S means sympify

In [20]:
S(1)/2

1/2

In [21]:
S(1)/2 + S(1)/3

5/6

### 多項式

In [22]:
x = sp.symbols('x') # let variable x be 'x'

In [23]:
f = x**2 + 2*x -3

In [24]:
f

x**2 + 2*x - 3

In [25]:
from sympy.abc import x, y, z

In [26]:
g = 3*x**2 + 5*x +4

In [27]:
g

3*x**2 + 5*x + 4

In [28]:
f + g

4*x**2 + 7*x + 1

### sympy 的矩陣運算:

In [29]:
A = sp.Matrix([[1, 2, 3], [4, 5, 6]])
A

Matrix([
[1, 2, 3],
[4, 5, 6]])

In [30]:
B = sp.Matrix([[1, 2], [2, 1], [1, 1]])
B

Matrix([
[1, 2],
[2, 1],
[1, 1]])

這樣就可以直接用```*```了。

In [31]:
C = A*B 

也可以用```inv()```表示反矩陣了。

In [36]:
C.inv() 

Matrix([
[19/12, -7/12],
[ -5/3,   2/3]])